/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Disporapar HST
 */
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;


public class Aplikasikeuanganpribadi extends javax.swing.JFrame {
 private Connection conn = Koneksi.connect(); // Ganti dengan koneksi dari class SetupDatabase

 private void updateSaldo() {
    try {
        // Query untuk menghitung total pemasukan dan pengeluaran
        String sql = "SELECT SUM(pemasukan) AS total_pemasukan, SUM(pengeluaran) AS total_pengeluaran FROM keuangan";
        PreparedStatement ps = conn.prepareStatement(sql);
        var rs = ps.executeQuery();
        
        // Jika data ada
        if (rs.next()) {
            double totalPemasukan = rs.getDouble("total_pemasukan");
            double totalPengeluaran = rs.getDouble("total_pengeluaran");
            double saldoTotal = totalPemasukan - totalPengeluaran;
            
            // Menampilkan saldo pada label saldo
            saldo.setText("Saldo : Rp. " + String.format("%,.2f", saldoTotal));
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error menghitung saldo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
   private void tambahData() {
    String tanggal, pengeluaran, pemasukan, keterangan;
    
    // Format tanggal menjadi String
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    tanggal = sdf.format(tgl.getDate());
    
    // Ambil nilai input
    pengeluaran = keluar.getText();
    pemasukan = masuk.getText();
    keterangan = ket.getText();
    
    // Validasi input kosong
    if (tanggal.isEmpty() || pengeluaran.isEmpty() || pemasukan.isEmpty() || keterangan.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Validasi hanya angka pada pengeluaran dan pemasukan
    if (!pengeluaran.matches("\\d+") || !pemasukan.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Pengeluaran dan Pemasukan harus berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        // Query untuk menambah data
        String sql = "INSERT INTO keuangan (tanggal, pengeluaran, pemasukan, keterangan) VALUES (?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        
        // Set parameter query
        ps.setString(1, tanggal);
        ps.setDouble(2, Double.parseDouble(pengeluaran));
        ps.setDouble(3, Double.parseDouble(pemasukan));
        ps.setString(4, keterangan);
        
        // Eksekusi query
        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        
        // Reset input
        tgl.setDate(null);
        keluar.setText("");
        masuk.setText("");
        ket.setText("");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menambahkan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
   
  
   
    /**
     * Creates new form Aplikasikeuanganpribadi
     */
    public Aplikasikeuanganpribadi() {
        initComponents();
        updateSaldo();
        tmbh.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        tmbhActionPerformed(evt); 
            updateSaldo();  // Memperbarui saldo setelah menambah data
    }
    

            private void tmbhActionPerformed(ActionEvent evt) {
                tambahData();
                
            }
        });
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tgl = new com.toedter.calendar.JDateChooser();
        keluar = new javax.swing.JTextField();
        masuk = new javax.swing.JTextField();
        ket = new javax.swing.JTextField();
        tmbh = new javax.swing.JButton();
        data = new javax.swing.JButton();
        saldo = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sakkal Majalla", 1, 36)); // NOI18N
        jLabel1.setText("Aplikasi Keuangan Pribadi");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 19)); // NOI18N
        jLabel2.setText("Pengeluaran");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 19)); // NOI18N
        jLabel3.setText("Pemasukan");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 19)); // NOI18N
        jLabel4.setText("Keterangan");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 19)); // NOI18N
        jLabel5.setText("Tanggal");

        tgl.setDateFormatString("dd-MM-yyyy");

        keluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        masuk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ket.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tmbh.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tmbh.setText("Tambah");
        tmbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbhActionPerformed(evt);
            }
        });

        data.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        data.setText("Lihat Data");
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });

        saldo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        saldo.setText("Saldo : Rp. ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(keluar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(masuk)
                            .addComponent(ket)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(57, 57, 57)
                                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(saldo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tmbh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(data, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ket, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(tmbh))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(data)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(saldo)
                        .addGap(20, 20, 20))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
        // TODO add your handling code here:  // Membuka jendela DataKeuanganPribadi
    new DataKeuanganPribadi().setVisible(true);
    this.dispose();  // Menutup jendela AplikasiKeuanganPribadi saat DataKeuanganPribadi terbuka
    }//GEN-LAST:event_dataActionPerformed

    private void tmbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbhActionPerformed
     
    }//GEN-LAST:event_tmbhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikasikeuanganpribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikasikeuanganpribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikasikeuanganpribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikasikeuanganpribadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikasikeuanganpribadi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField keluar;
    private javax.swing.JTextField ket;
    private javax.swing.JTextField masuk;
    private javax.swing.JLabel saldo;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JButton tmbh;
    // End of variables declaration//GEN-END:variables
}
